[package]
name = "rusty_casino"
version = "0.1.0"
authors = ["Michael Jenkins <mtj4@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
shuffle = "0.1.3"
text_io = "0.1.8"
